from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.session_out,name='login'),
    url(r'^home/$',views.home,name='home'),
    url(r'^incorrect/$',views.incorrect,name='incorrect'),
    url(r'^adminHome/$',views.adminHome,name='adminhome'),
    url(r'^register/$',views.register,name='register'),
    url(r'^sign_up/$',views.signup,name='signup'),
    url(r'^order/$',views.order,name='order'),
    url(r'^pending/$',views.pending,name='pending'),
    url(r'^ChangeStatus/$',views.ChangeStatus,name='ChangeStatus'),
    url(r'^change/$',views.change,name='change'),
    url(r'^confirmed/$',views.confirmed,name='confirmed'),
    url(r'^cleanConfirmed/$',views.cleanConfirmed,name='cleanConfirmed'),
    url(r'^newRate/$',views.newRate,name='newRate'),
    url(r'^changeRate/$',views.changeRate,name='changeRate'),
    url(r'^incr/$',views.incr,name='incr'),
    url(r'^addStock/$',views.addStock,name='addStock'),
    url(r'^about/$',views.about,name='about'),
    url(r'^rates/$',views.rates,name='rates'),
    url(r'^myOrders/$',views.myOrders,name='myOrders'),
    url(r'^rworker/$',views.rworker,name='rworker'),
    url(r'^wregister/$',views.wregister,name='wregister'),
    url(r'^delete/$',views.delete,name='delete'),
    url(r'^cdelete/$',views.cdelete,name='cdelete'),
    url(r'^attendance/$',views.attendance,name='attendance'),
    url(r'^markAttend/$',views.markAttend,name='markAttend'),
    url(r'^pswd/$',views.pswd,name='pswd'),
    url(r'^chgPaswd/$',views.chgPaswd,name='chgPaswd'),
    url(r'^payWorker/$',views.payWorker,name='payWorker'),
    url(r'^paySuccess/$',views.paySuccess,name='paySuccess'),
    url(r'^allPay/$',views.allPay,name='allPay'),
    url(r'^cleanPayment/$',views.cleanPayment,name='cleanPayment'),
    url(r'^workerPayment/$',views.workerPayment,name='workerPayment'),
    url(r'^payInd/$',views.payInd,name='payInd'),
    url(r'^successfulTransact/$',views.successfulTransact,name='successfulTransact'),
    url(r'^failedTransact/$',views.failedTransact,name='failedTransact'),
]
